config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }
  resources :jobs do
    puts :update_status  
    resources :bids, shallow: true
  end

  resources :users, only: [:show]

  resources :job_skills

  resources :users, only: [:show] do
    resources :skills do
      resources :votes
    end
  end

  resources :skills

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  def index
    @job = Job.find(params[:job_id])
    @bids = Bid.all
  end

  def show
    #we cannot show :job_id
    # @job = Job.find(params[:job_id])
  end

  def new
    @job = Job.find(params[:job_id])
    @bid = @job.bids.new
    @bid.user_id = current_user.id
  end

  def edit
  end

  def create
    @job = Job.find(params[:job_id])
    @bid = @job.bids.new(bid_params)
    @bid.user_id = current_user.id
    if @bid.save
      redirect_to @bid
    else
      render :new
    end
  end

  def update
    if @bid.update(bid_params)
      redirect_to @bid
    else
      render :edit
    end
  end

  def destroy
    @bid.destroy
    redirect_to job_bids_path(@bid.job_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:bid_value, :bid_status)
    end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for([@job, @bid]) do |f| %>
	<% if @bid.user.id == current_user.id && @bid.bid_status == 0 %>
		<div class="field">
		  <%= f.label :bid_value %><br>
		  <%= f.number_field :bid_value %>
		</div>
		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', job_path(@bid.job_id) %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bids</h1>

<table>
  <thead>
    <tr>
      <th>Bid value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% i = 1 %>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= i %>) <%= bid.job.name %></td>
        <td>|  <%= bid.user.fullname %></td>
        <td>|  <%= bid.bid_value %></td>
        <td>|  <%= link_to 'Show', bid %></td>
        <% if bid.user.id == current_user.id && bid.job.job_status == 0 %>
          <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
          <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% i += 1 %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_job_bid_path %>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job Title:</strong>
  <%= @bid.job.name %> <br>
  <strong>Job Poster:</strong>
  <%= @bid.job.user.fullname %> <br>
  <strong>Bid value:</strong>
  <%= @bid.bid_value %> <br>
  <strong>Bidder: </strong>
  <%= @bid.user.fullname %>
</p>

<% if @bid.user.id == current_user.id && @bid.bid_status == 0 %>
	<%= link_to 'Edit', edit_bid_path(@bid) %> |
<% end %>
<%= link_to 'Back', job_path(@bid.job_id) %>