config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }
  resources :jobs do
    puts :update_status  
    resources :bids, shallow: true
  end

  resources :users, only: [:show]

  resources :job_skills

  resources :users, only: [:show] do
    resources :skills do
      resources :votes
    end
  end

  resources :skills

end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	has_many :job_skills
	serialize :required_skills
	has_many :bids

	searchkick

	def has_skill?(skill)
  	return false if required_skills.nil?
	  required_skills.include?(skill) 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_jobs, only: [:show, :edit, :update, :destroy]
  def new
    @job = Job.new
    @job_skills = JobSkill.all
  end

  def create
    @job = current_user.jobs.new(job_params)

    job_skill = []
    if !params[:required_skills].nil?
      params[:required_skills].each_key do |key|
        job_skill << key
      end
    end 
    @job.required_skills = job_skill
    if @job.save

      Job.reindex
      redirect_to jobs_path, notice: "Job Created"
    end
  end

  def edit
    @job_skills = JobSkill.all
  end

  def show
  end

  def update
    job_skill = []
    if !params[:required_skills].nil?
      params[:required_skills].each_key do |key|
        job_skill << key
      end
    end 
    @job.required_skills = job_skill
    if @job.update(job_params)

      Job.reindex
      redirect_to jobs_path, notice: "Job Updated"
    end
  end

  def index
    query = params[:q].presence || "*"
    @jobs = Job.search(query).to_a.flatten.uniq
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    Job.reindex

    redirect_to jobs_path, notice: "Job Deleted"
  end

  private
  def set_jobs
    @job = Job.find(params[:id])
  end

  def job_params
  	params.require(:job).permit(:name, :pay_offer, :job_status, :required_skills)
  end
end

app/views/jobs/edit.html.erb
<center>
<div>
	<%= form_for(@job) do |f| %>
		<div>
			<%= f.label :name %>
			<%= f.text_field :name%>
		</div>
		<div>
			<%= f.label :pay_offer %>
			<%= f.text_field :pay_offer%>
		</div>
		
		<%= f.label :required_skills %>
		<% @job_skills.all.each do |jobskill| %>
			<%= check_box_tag "required_skills[#{jobskill.skill}]", "#{jobskill.skill}]", @job.has_skill?(jobskill.skill) %><%= jobskill.skill %><br>
		<% end %>

		<%= f.submit :'Update Job', class: "btn btn-default" %>
		</div>
	<% end %>
</div>
</center>

app/views/jobs/index.erb
<%= form_tag jobs_path, :method => 'get',class: "navbar-form" do%>
	<div class="input-group">
		<%=text_field_tag :q, nil, placeholder: "Search Jobs", class: 'form-control'%>
		<span class="input-group-btn">
			<%= button_tag(type: 'submit', class: 'btn btn-default') do %>
  			<span
    			class="glyphicon glyphicon-search">
  			</span>
  			<%end%>
  		</span>
	</div>  
<%end%>

<%if @jobs.any?%>
	<% i = 1%>
	<%@jobs.each do |job|%>
		<% user= job.user%>
		<div class="col-sm-6">
			<h3><%=i%>. <%=job.name%></h3>
			<label>Pay Offer: </label><%= job.pay_offer%><br>
			<label>Required Skills: </label><%= job.required_skills.join(" ") if !job.required_skills.nil? %><br>
			<label>by</label> <%= user.fullname%><br>
			<%= link_to "Edit", edit_job_path(job), class: "btn btn-default"%>
			<%= link_to job_path(job), method: :delete, class: "btn btn-default" do %>
			    <i class="glyphicon glyphicon-remove"></i>
			<% end %>
		</div>
		<% i = i+1%>
	<%end%>
<%else%>
	<label>No jobs yet</label>
<%end%>

app/views/jobs/index.html.erb
<%= form_tag jobs_path, :method => 'get',class: "navbar-form" do%>
	<div class="input-group">
		<%=text_field_tag :q, nil, placeholder: "Search Jobs", class: 'form-control'%>
		<span class="input-group-btn">
			<%= button_tag(type: 'submit', class: 'btn btn-default') do %>
  			<span
    			class="glyphicon glyphicon-search">
  			</span>
  			<%end%>
  		</span>
	</div>  
<%end%>
<!-- The Searchbar  -->



<%if @jobs.any?%>
	<% i = 1%>
	<%@jobs.each do |job|%>
		<% user= job.user%>
		<div class="col-sm-3">
		<h3><%=i%>. <a href="/jobs/<%= job.id %>"><%=job.name%></a></h3>
		<label>Price: </label><%= job.pay_offer%><br>
		<label>Required Skills: </label> <%= job.required_skills.join(", ") if !job.required_skills.nil? %><br>
			<% if job.bids.count != 0 %>
				<label>Bids: </label><%= job.bids.count %>
			<% else %>
				<label>No Bids Yet</label>
			<% end %>
			<!-- To show the amount of bids if there is any -->



			<% if current_user.id == user.id && job.job_status == 0 %>
				<%= link_to "Edit the job you posted", edit_job_path(job), class: "btn btn-default" %>
				<%= link_to job_path(job), method: :delete, class: "btn btn-default" do %>
			    <i class="glyphicon glyphicon-remove"></i>
				<% end %>
			<!-- You edit the job if you're the person who posted it -->



			<% elsif current_user.id == user.id && job.job_status == 1 %>
				<button class="btn btn-default">Talk to your developer</button>


			<% else %>
				<% if job.bids.where(user_id: current_user.id).count == 0 %>
					<% if job.job_status == 1 %>
						<button class="btn btn-default">Bidding is closed</button>
					<% else %>
						<%= link_to 'You can bid on this project', new_job_bid_path(job), class: "btn btn-default" %>
					<% end %>
			<!-- To stop people from bidding if the job has been won. Otherwise, you can bid if you haven't yet bid on the job -->



				<% else %>
					<% job.bids.each do |bid| %>
						<% if bid.user_id == current_user.id %>
							<% if job.job_status == 1 %>
								<button class="btn btn-default">Contact your customer</button>
							<% else %>
								<%= link_to 'Adjust your bid', edit_bid_path(bid), class: "btn btn-default" %>
							<% end %>
				<!-- If you have already bid on the job (and it hasn't been won), you can adjust you bid -->


						<% end %>
					<% end %>
				<% end %>
			<% end %>
		</div>
		<% i = i+1%>
	<%end%>
<%else%>
	<label>No jobs yet</label>
<%end%>

app/views/jobs/new.html.erb
<center>
<div>
	<%= form_for(@job) do |f| %>
		<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
		</div>
		<div>
		<%= f.label :pay_offer %>
		<%= f.text_field :pay_offer%>
		</div>

		<%= f.label :required_skills %>
		<% @job_skills.all.each do |jobskill| %>
			<%= check_box_tag "required_skills[#{jobskill.skill}]" %><%= jobskill.skill %><br>
		<% end %>

		<div>
		<%= f.submit :'Create Job', class: "btn btn-default" %>
		</div>
	<% end %>
</div>
</center>

app/views/jobs/show.html.erb
	<div>
	<h3><%= @job.name %></h3><br>
	Job Pay : <%= @job.pay_offer %><br>
	Job Owner : <%= @job.user.fullname %> <br>
	Skills Required : <%= @job.required_skills.join(", ") %><br>
	Job Status :
		<% if @job.job_status == 0 %>
			Open for bidding
		<% elsif @job.job_status == 1 %>
			Bidding closed	
	<% end %>
</div>
<!-- This part on top works! It works to show the status of the job -->


		<% if @job.bids.count != 0 %>
			<% @job.bids.each do |bid|  %>
				<% if bid.bid_status == 1 %>
					<% bid.job.bids.where(bid_status: 0).destroy_all %>
					<% @job.job_status = 1 %>
					<% @job.save %>
					<% @winner = true %>
				<!-- Job save works! We now update the status of the job when a bid is accepted -->


				<% end %>
			<% end %>
		<% end %>


<div class="col-sm-3">
	<% if current_user.id != @job.user.id %>
		<% if @job.bids.where(user_id: current_user.id).count == 0 %>
			<% if @winner == true %>
			<% else %>
				<%= link_to 'New Bid', new_job_bid_path(@job), class: "btn btn-default" %>
			<% end %>



	<!-- To prevent new bids to be lodged when there is a winner -->

		<% elsif @job.bids.where(user_id: current_user.id).count != 0  %>
			<% @job.bids.each do |bid| %>
				<% if bid.user_id == current_user.id && bid.bid_status == 0 %>
					<%= link_to 'Edit Your Bid', edit_bid_path(bid), class: "btn btn-default" %>
				<% elsif bid.user_id == current_user.id && bid.bid_status == 1 %>
					<button class="btn btn-default">Talk to your customer</button>
				<% end %>
			<% end %>
		<% end %>
	<% elsif @winner == true %>
			<button class="btn btn-default">Talk to your developer</button>
	<% else %>
		<%= link_to "Edit", edit_job_path, class: "btn btn-default" %>
		<%= link_to job_path, method: :delete, class: "btn btn-default" do %>
	    <i class="glyphicon glyphicon-remove"></i>
		<% end %>
	<% end %>
	<%= link_to "Back", jobs_path, class: "btn btn-default" %>
	<br><br>
<!-- The part on top helps us create a button to bid if we haven't, edit the bid if we have. And edit the job if we own the job instead-->



	<div>
		<% if @job.bids.count != 0 %>
			<% if @winner == true %>
				<label>Winning Bid</label><br>
			<% else %>
				<label>Current Bid</label><br>
			<% end %>
			<% @job.bids.each do |bid|  %>
				<div>
				<% if bid.user.id == current_user.id %>
					Your Bid
				<% else %>
					<%= bid.user.fullname %>
				<% end %>
				<%= bid.bid_value %>

<!-- We show the bid details for current bids, if there's any. If there are no bids, this will not show -->


					<% if @job.user_id == current_user.id %>
						<%= form_for bid do |f| %>
							<%= f.hidden_field :bid_status, value: 1 %>
							<% if @winner == true %>
							<% else %>
								<%= f.submit "Accept bid" %>
							<% end %>
						<% end %>
					<% end %>
<!-- The top part let's us accept the bid if we're the job owner -->

				

				</div>
			<% end %>			
		<% else %>
		 No Bids Yet
		<% end %>
	</div>
</div>

<!--
<script>
$.ajax({
	  method: "POST",
	  url: "some.php",
	  data: { name: "John", location: "Boston" }
	})
	  .done(function( msg ) {
	    alert( "Data Saved: " + msg );
	  });
</script>
-->