config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                                :registrations => 'registrations'
                              }
  resources :jobs do
    puts :update_status  
    resources :bids, shallow: true
  end

  resources :users, only: [:show]

  resources :job_skills

  resources :users, only: [:show] do
    resources :skills do
      resources :votes
    end
  end

  resources :skills

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :user
	belongs_to :job
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_with_omniauth(auth)
    find_by(uid: auth['uid'], provider: auth['provider'])
  end

  def self.create_with_omniauth(auth)
    create(uid: auth['uid'], provider: auth['provider'])
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	has_many :job_skills
	serialize :required_skills
	has_many :bids

	searchkick

	def has_skill?(skill)
  	return false if required_skills.nil?
	  required_skills.include?(skill) 
  end
end

app/models/job_skill.rb
class JobSkill < ActiveRecord::Base
  has_many :jobs
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  validates_uniqueness_of :skill, :scope => :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :skills
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :identities
  has_many :bids
  has_many :jobs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
         
  validates :fullname, presence: true, length: {maximum: 50}
  validates_uniqueness_of :user_skills
  # validates :email, uniqueness: true, allow_nil: true

  has_many :jobs
  has_many :skills
  has_many :votes
  serialize :user_skills

  def self.from_omniauth(auth)
  	user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def has_skill?(skill)
    return false if user_skills.nil?
    user_skills.include?(skill) 
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
  validates_uniqueness_of :up_vote, :scope => [:skill_id, :user_id] 
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  def index
    @job = Job.find(params[:job_id])
    @bids = Bid.all
  end

  def show
    #we cannot show :job_id
    # @job = Job.find(params[:job_id])
  end

  def new
    @job = Job.find(params[:job_id])
    @bid = @job.bids.new
    @bid.user_id = current_user.id
  end

  def edit
  end

  def create
    @job = Job.find(params[:job_id])
    @bid = @job.bids.new(bid_params)
    @bid.user_id = current_user.id
    if @bid.save
      redirect_to @bid
    else
      render :new
    end
  end

  def update
    if @bid.update(bid_params)
      redirect_to @bid
    else
      render :edit
    end
  end

  def destroy
    @bid.destroy
    redirect_to job_bids_path(@bid.job_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:bid_value, :bid_status)
    end
end

app/controllers/job_skills_controller.rb
class JobSkillsController < ApplicationController
	def new
		@job_skill = JobSkill.new
	end

	def create
		@job_skill = JobSkill.new(job_skill_params)
		if @job_skill.save
			redirect_to root_path
		end
	end

	private
	def job_skill_params
		params.require(:job_skill).permit(:skill)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_jobs, only: [:show, :edit, :update, :destroy]
  def new
    @job = Job.new
    @job_skills = JobSkill.all
  end

  def create
    @job = current_user.jobs.new(job_params)

    job_skill = []
    if !params[:required_skills].nil?
      params[:required_skills].each_key do |key|
        job_skill << key
      end
    end 
    @job.required_skills = job_skill
    if @job.save

      Job.reindex
      redirect_to jobs_path, notice: "Job Created"
    end
  end

  def edit
    @job_skills = JobSkill.all
  end

  def show
  end

  def update
    job_skill = []
    if !params[:required_skills].nil?
      params[:required_skills].each_key do |key|
        job_skill << key
      end
    end 
    @job.required_skills = job_skill
    if @job.update(job_params)

      Job.reindex
      redirect_to jobs_path, notice: "Job Updated"
    end
  end

  def index
    query = params[:q].presence || "*"
    @jobs = Job.search(query).to_a.flatten.uniq
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    Job.reindex

    redirect_to jobs_path, notice: "Job Deleted"
  end

  private
  def set_jobs
    @job = Job.find(params[:id])
  end

  def job_params
  	params.require(:job).permit(:name, :pay_offer, :job_status, :required_skills)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def show
    @skill = Skill.find(params[:id])
  end

	def new
    @user = current_user
  	@skill = Skill.new
    @vote = Vote.new
  end

  def create
  	@skill = Skill.new(skill_params)
  	if @skill.save

  		redirect_to user_path(current_user.id), notice: "Skill Added"
  	end
  end
  
  private
  def skill_params
  	params.require(:skill).permit(:skill)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:show, :edit, :update, :destroy]

  def show
  end

  private
	def set_users
		@user = User.find(params[:id])
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def new
    @user = User.find(params[:user_id])
    @skill = Skill.find(params[:skill_id])
  	@vote = Vote.new
  end

  def create
  	@vote = Vote.new(vote_params)
  	@vote.user_id = current_user.id
    @vote.skill_id = params[:skill_id]
    @skill = Skill.find(params[:skill_id])
    # if !Vote.exists?(:user_id => current_user.id) && @vote.user_id == current_user.id
    #   redirect_to user_path(current_user.id), notice: "U've alraedy voted for this"
    # else
    if @vote.save
      redirect_to :back, notice: "Thank You for your vote on #{@skill.skill}"
    else
      redirect_to :back, notice: "You've already voted on #{@skill.skill}"
  	end
  end
  
  def update
    @vote = Vote.find(params[:id])
    @vote.update(update_vote_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    redirect_to :back, notice: "Vote Destroyed"
  end

  private
  def vote_params
  	params.permit(:up_vote, :down_vote)
  end

  def update_vote_params
    params.permit(:up_vote, :down_vote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		if user.image
			user.image + "?type=large"
		else
		"https://www.gravatar.com/avatar.jpg?d=identical&s=150"
		end
	end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/job_skills_helper.rb
module JobSkillsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contractr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render "shared/navbar" %>
   <%= render "shared/message" %>
    <div class="container">
    	<%= yield %>
    </div> <!-- /container -->


</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CONTRACTR</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
            <%= current_user.fullname %><span class="caret"></span></a>
            
            <ul class="dropdown-menu">
              <li><%= link_to "Create A Job", new_job_path %></li>
              <li><%= link_to "All Jobs", jobs_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "User Profile", user_path(current_user.id) %></li>
              <li><a href="#">Account Settings</a></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>